# Generated by Django 5.1.5 on 2025-01-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_passeio', models.CharField(max_length=200)),
                ('descricao_passeio', models.TextField()),
                ('cronograma_passeio', models.TextField()),
                ('preco_pacote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viagens.agencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
