# Generated by Django 5.1.5 on 2025-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_passeio'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='novo_campo_teste',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
