# Generated by Django 5.1.5 on 2025-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_destinos_novo_campo_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinos',
            name='novo_campo_teste',
        ),
    ]
