# Generated by Django 5.1.5 on 2025-01-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_remove_destinos_novo_campo_teste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_rota', models.CharField(max_length=15)),
                ('descricao_rota', models.TextField(blank=True, null=True)),
                ('imagem_rota', models.ImageField(blank=True, null=True, upload_to='viagens_imagens/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
