# Generated by Django 5.1.5 on 2025-01-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_ecologica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecologica',
            name='imagem_rota',
        ),
    ]
