# Generated by Django 5.1.5 on 2025-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0006_remove_ecologica_imagem_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecologica',
            name='imagem_rota',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_imagens/'),
        ),
    ]
