# Generated by Django 5.1.5 on 2025-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0008_alter_ecologica_nome_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecologica',
            name='nome_rota',
            field=models.CharField(max_length=55),
        ),
    ]
