# Generated by Django 5.1.5 on 2025-01-23 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0009_alter_ecologica_nome_rota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pousada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pousada', models.CharField(max_length=30)),
                ('descricao_pousada', models.TextField()),
                ('preco_pousada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_pousada', models.ImageField(blank=True, null=True, upload_to='viagens_imagens/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
