# Generated by Django 5.1.5 on 2025-01-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_pousada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pousada',
            name='nome_pousada',
            field=models.CharField(max_length=35),
        ),
    ]
