# Generated by Django 5.1.5 on 2025-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0011_alter_pousada_nome_pousada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_carro', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='viagens_image/')),
            ],
        ),
    ]
