# Generated by Django 5.1.5 on 2025-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0012_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='nome_carro',
            field=models.CharField(max_length=20),
        ),
    ]
