# Generated by Django 5.1.5 on 2025-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0013_alter_aluguel_nome_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='imagem_passeio',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_imagens/'),
        ),
    ]
