# Generated by Django 5.1.5 on 2025-02-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0014_passeio_imagem_passeio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='destinos',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='passeio',
            name='preco_pacote',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
    ]
