# Generated by Django 5.1.2 on 2025-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0015_remove_aluguel_descricao_remove_aluguel_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinos',
            name='imagem_praia1',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='destinos',
            name='imagem_praia2',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='destinos',
            name='imagem_praia3',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
    ]
