# Generated by Django 5.1.2 on 2025-02-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0016_destinos_imagem_praia1_destinos_imagem_praia2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsApp', models.CharField(max_length=11, null=True)),
                ('instagram', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('email', models.TimeField(null=True)),
            ],
        ),
    ]
