# Generated by Django 5.1.2 on 2025-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0017_negociar'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='imagem_passeio1',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='imagem_passeio2',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='imagem_passeio3',
            field=models.ImageField(blank=True, null=True, upload_to='viagens_image/'),
        ),
    ]
