# Generated by Django 5.1.2 on 2025-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0018_passeio_imagem_passeio1_passeio_imagem_passeio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='descricao_veiculo',
            field=models.TextField(null=True),
        ),
    ]
